### ISSUE TITLE
[PE-D][Tester C] Docs: Broken hyperlinks in table of contents

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-T13-2/tp#182] opened 2023-11-03 21:33 UTC
Some hyperlinks do not work and redirect such as "update photo" and notes features

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: nicleongyj/ped#3

**Comment by lordidiot** [comment] 2023-11-04 05:20
Closed as duplicate of #165

**Closed as not planned by lordidiot** 2023-11-04 05:20 UTC
Labels: severity.VeryLow, triaged.Bug
